version: "3.7" 
services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    restart: always
    volumes:
       - ./:/var/www
       - ./default.conf:/etc/nginx/conf.d/default.conf
            
    ports:
      -"80:80"
    
  flask:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    expose: 
      - 8080
    aliases:
      - flask-app